return {
	'danielfalk/smart-open.nvim',
	branch = '0.2.x',
	enabled = true,
	keys = {
		{
			'<leader>ff',
			function()
				require('telescope').extensions.smart_open.smart_open({
					cwd_only = true,
					match_algorithm = 'fzy',
					open_buffer_indicators = { others = ' ', previous = ' ' },
					ignore_patterns = {
						'*~',
						'~:',
						'*.7z',
						'*.apk',
						'*.avif',
						'*.bak',
						'*.bin',
						'*.bmp',
						'*build/*',
						'*.bz2',
						'*.class',
						'*.ctags',
						'*.cur',
						'*.db',
						'*debug/*',
						'*.dll',
						'*.doc',
						'*.doc',
						'*.DS_Store',
						'*.gif',
						'*.git/*',
						'*.gz',
						'*.heif',
						'*.ico',
						'*.ico',
						'*.jar',
						'*.jpeg',
						'*.jpg',
						'*.jxl',
						'*.lock',
						'*.lzma',
						'*.min.gzip.js',
						'*.min.js',
						'*.node',
						'oil',
						'*.otf',
						'*.pack',
						'*.pcf',
						'*.pdb',
						'*.pdf',
						'*.pdf',
						'*.png',
						'*.ppt',
						'*.pyc',
						'*.rar',
						'*.rlib',
						'*.rmeta',
						'*.ser',
						'*.sfd',
						'*.so',
						'*.so',
						'*.spl',
						'*.svg',
						'*.swp',
						'*.tif',
						'*.tiff',
						'*.ttf',
						'*.wasm',
						'*.woff*',
						'*.xls',
						'*.zip',
					},
				})
			end,
			desc = '[F]ind Smart Open',
		},
	},
	config = function()
		require('telescope').load_extension('smart_open')
	end,
}
