#  https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

call_parentheses = "Always"
column_width = 120
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
quote_style = "ForceSingle"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
