return {
	'tpope/vim-fugitive',
	keys = {
		{ '<leader>ga', '<cmd>G add %<cr>', desc = 'Git add' },
		{ '<leader>gal', '<cmd>G add --all<cr>', desc = 'Git add all' },
		{ '<leader>gap', '<cmd>G add % -p<cr>', desc = 'Git add partial' },
		{ '<leader>gbm', ':G branch -m ', desc = 'Git branch move' },
		{ '<leader>gca', '<cmd>:G commit --amend<cr>', desc = 'Git commit amend' },
		{ '<leader>gcm', '<cmd>G commit<cr>', desc = 'Git commit' },
		{ '<leader>g', '<cmd>:G<cr>', desc = 'Git (Fugitive)' },
		{ '<leader>gfa', '<cmd>G fetch --all -p<cr>', desc = 'Git fetch all' },
		{ '<leader>gi', '<cmd>G init<cr>', desc = 'Git init' },
		{ '<leader>gma', '<cmd>G merge --abort<cr>', desc = 'Git merge abort' },
		{ '<leader>gm', ':G merge --no-ff --no-edit ', desc = 'Git merge' },
		{ '<leader>gp', '<cmd>G push<cr>', desc = 'Git push' },
		{ '<leader>gpf', '<cmd>G push origin -f HEAD<cr>', desc = 'Git push origin force' },
		{ '<leader>gpl', '<cmd>G pull<cr>', desc = 'Git pull' },
		{ '<leader>gpo', '<cmd>G push origin -u HEAD<cr>', desc = 'Git push origin' },
		{ '<leader>gu', ':G reset --soft HEAD~1', desc = 'Git undo' },
		{ '<leader>sum', ':G stash -um ', desc = 'Git stash' },
	},
}
